#!/usr/bin/env python3
"""
test_enrich.py — Test the new Gemini text_nl prompt on just the 11 failing questions.

Shows:
  - The question that failed retrieval
  - The target chunk's current text_nl (old MLX version)
  - The new text_nl generated by Gemini
  - Side-by-side comparison

Run:
    python test_enrich.py
"""

import json
import os
import time
from pathlib import Path

import google.generativeai as genai
from dotenv import load_dotenv

load_dotenv()

# ── Config ────────────────────────────────────────────────────────────────────

GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

SYSTEM_PROMPT = (
    "You are a government data analyst. Your job is to convert a markdown table "
    "into exhaustive, searchable natural language. "
    "For EVERY data row, write one sentence that states the row label and ALL its "
    "column values explicitly — include every number, percentage, and dollar amount. "
    "Do NOT summarize, skip rows, or describe trends. "
    "Every value in the table must appear verbatim in your output."
)

USER_TEMPLATE = """\
Convert every row of this table into natural language. \
State the row label and all its column values explicitly. \
Do not skip any rows or summarize.

Report: Canadian Employment Insurance Monitoring and Assessment Report, fiscal year {fiscal_year}
Section: {section_breadcrumb}

{text}"""

# ── Setup ─────────────────────────────────────────────────────────────────────

api_key = os.getenv("GOOGLE_API_KEY")
if not api_key:
    raise SystemExit("GOOGLE_API_KEY not found")
genai.configure(api_key=api_key)
model = genai.GenerativeModel(
    model_name=GEMINI_MODEL,
    system_instruction=SYSTEM_PROMPT,
)

# ── Load the 11 missed questions ──────────────────────────────────────────────

results_path = Path("data/eval/retrieval_results.json")
if not results_path.exists():
    raise SystemExit("data/eval/retrieval_results.json not found — run evaluate_retrieval.py first")

retrieval = json.load(open(results_path))
misses = retrieval.get("misses", [])
print(f"Found {len(misses)} missed questions in retrieval results\n")

# ── Load all chunks indexed by chunk_id ───────────────────────────────────────

all_chunks = {}
for f in Path("data/chunked").glob("*.jsonl"):
    for line in open(f):
        c = json.loads(line)
        all_chunks[c["chunk_id"]] = c

print(f"Loaded {len(all_chunks)} chunks total\n")

# ── Test each missed question ─────────────────────────────────────────────────

for i, miss in enumerate(misses, 1):
    target_id   = miss["target_id"]
    question    = miss["question"]
    chunk_type  = miss["chunk_type"]
    fiscal_year = miss["fiscal_year"]

    print(f"{'='*70}")
    print(f"[{i}/{len(misses)}] {fiscal_year} | {chunk_type}")
    print(f"Q: {question}")
    print(f"Target chunk: {target_id}")

    chunk = all_chunks.get(target_id)
    if not chunk:
        print("  ⚠ Chunk not found in index!")
        print()
        continue

    # Show current text_nl
    current_nl = chunk.get("text_nl", "(none)")
    print(f"\n--- CURRENT text_nl (old) ---")
    print(current_nl[:600] + ("..." if len(current_nl) > 600 else ""))

    # Show raw table (first 400 chars)
    raw_table = chunk.get("text", "")
    print(f"\n--- RAW table (first 400 chars) ---")
    print(raw_table[:400] + ("..." if len(raw_table) > 400 else ""))

    # Generate new text_nl with Gemini
    print(f"\n--- NEW text_nl (Gemini {GEMINI_MODEL}) ---")
    try:
        prompt = USER_TEMPLATE.format(
            fiscal_year=chunk.get("fiscal_year") or "Unknown",
            section_breadcrumb=chunk.get("section_breadcrumb") or "Unknown",
            text=chunk["text"],
        )
        resp = model.generate_content(prompt)
        new_nl = resp.text.strip()
        print(new_nl[:800] + ("..." if len(new_nl) > 800 else ""))

        # Quick check: does the new text_nl contain any of the top5 retrieved IDs context?
        print(f"\n--- VERDICT ---")
        print(f"Old length: {len(current_nl)} chars")
        print(f"New length: {len(new_nl)} chars")
        if len(new_nl) > len(current_nl):
            print("✓ New text_nl is longer (more detail captured)")
        else:
            print("⚠ New text_nl is shorter or same length")

    except Exception as e:
        print(f"  ERROR: {e}")

    time.sleep(1)  # rate limit
    print()

print("="*70)
print("Test complete.")
